### ISSUE TITLE
Azure Functions plugin requires Java 11

### ISSUE THREAD

**Issue by Zarick** [microsoft/azure-gradle-plugins#109]
The latest release of azure functions gradle plugin requires Java 11 as the Jars compilation target is class file version 55.

Is there any specific reason for bumping the class version?

**Comment by andxu** [comment]
Thanks for the notification, we will release soon(today) , the next version will 1.7.0 will be able to run on Java 8.

**Comment by andxu** [comment]
1.7.0 is released
