### ISSUE TITLE
Support deployment slots

### ISSUE THREAD

**Issue by jensbarthel** [microsoft/azure-gradle-plugins#132]
## Motivation
Lacking the ability to deploy to slots (with auto-switch capabilities) complicates the production use of this plugin. Even more so in continuous delivery environments.

## Proposed feature
Support deployment to slots, analogous to the [deployment slot feature](https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Functions:-Configuration-Details#deployment-slot) in the sister maven plugin.

**Comment by Flanker32** [comment]
@jensbarthel Deployment slot support  for Gradle plugin for azure functions (1.9.0)/webapp(1.4.0) has been released, you may try this feature with following configuration.
```
azurefunctions {
    ...
    deploymentSlot {
      name = 'xxx'
      configurationSource = 'parent'
    }
}
```

**Comment by jensbarthel** [comment]
Nice, thanks for the update. :+1: 
I'll check it out!

**Comment by jensbarthel** [comment]
Works like a charm, we have updated our production environment accordingly.
Thanks! :heart:
